name: My First Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: |
            echo "First output"
            echo "Secpnd output"
      - name: print good-bye
        run: echo "Good Bye!"
